"""``ReportModel`` — everything a template is allowed to see (ROADMAP M3, DESIGN.md §9.1).

**Every leaf below is a ``str``, a ``bool``, an ``int``, a :class:`~investo.report.charts.ChartImage`
or a sequence of those. No ``Decimal`` and no ``Fact`` reaches a template.** That single rule is
CLAUDE.md convention 14, and three guarantees fall out of it rather than needing to be checked:

- **A template cannot compute a figure**, because the figure is already a string. A number computed
  in a template has no ``Fact`` behind it, is absent from ``report.json``, and is invisible to every
  test that walks this model — and it is the most natural thing to write when the template is two
  lines from the data. The AST check over the template source is a second lock on a door this
  module already shut.
- **The appendix cannot disagree with an axis label**, because both are produced by
  :mod:`investo.report.format` from the same ``Decimal``.
- **Everything printable is decided in Python**, where it is unit-testable without rendering
  anything — which matters because rendering costs a WeasyPrint import and a PDF.

This module is also where the three *derived* series live. Free cash flow, the margins and the
year-over-year growth rate are computed here, over ``Decimal``, each producing a
:class:`~investo.domain.provenance.Derivation` naming both inputs — so a point on a chart traces
exactly like a filed value. They are not computed in ``charts.py`` (a chart module that does
arithmetic can print a number nothing else knows about) and not in ``normalize/`` (they are
presentation, and §3.2's ``FinancialHistory`` is a record of what was *filed*).

**Both inputs are required, per period, with no interpolation.** A margin for a year with revenue
and no gross profit is not computed and not plotted; the point is dropped. Carrying the previous
year's numerator forward would draw a flat segment that reads as stability and means "missing".
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date
from itertools import pairwise
from typing import Final

from investo.domain.models import Fact, Metric
from investo.domain.provenance import Derivation, Provenance
from investo.normalize.statements import Bucket, FinancialHistory, MetricCoverage
from investo.normalize.tags import Tier, metrics_in_tier
from investo.report import format as fmt
from investo.report.charts import (
    SERIES_MUTED,
    SERIES_PRIMARY,
    SERIES_SECONDARY,
    SERIES_TERTIARY,
    ChartImage,
    ChartKind,
    ChartSpec,
    Datum,
    PlotSeries,
    build,
)
from investo.report.serialize import RunInfo, intern_sources

__all__ = [
    "DISCLAIMER",
    "NOT_ASSESSED",
    "ABSENT_SECTIONS",
    "Row",
    "Table",
    "Cover",
    "Snapshot",
    "HistorySection",
    "Caveats",
    "Appendix",
    "ReportModel",
    "build_model",
    "free_cash_flow",
    "margin_series",
    "yoy_series",
]

DISCLAIMER: Final = (
    # "This software", not "This report" — README § Disclaimer is the canonical wording and the two
    # are compared verbatim by `test_render::test_disclaimer_matches_readme`. Paraphrasing legal text
    # to fit its context is how two versions of it come to exist.
    "This software is for educational and informational purposes only. It is not investment "
    "advice, not a recommendation to buy or sell any security, and does not create an advisory "
    "relationship. Output is generated by statistical models from historical data and will be "
    "wrong. Past performance does not indicate future results. Do your own research and consult "
    "a licensed financial advisor before making investment decisions."
)
"""README § Disclaimer, verbatim. §10 requires it *prominent*, so it is on the cover in body type.

Duplicated from README rather than read from it: a renderer that parses a markdown file to find its
own disclaimer has made the legal text depend on a heading nobody thinks of as load-bearing.
``test_render::test_disclaimer_matches_readme`` compares the two instead.
"""

NOT_ASSESSED: Final = "NOT ASSESSED"
"""The verdict badge at M3, and it is deliberately a badge rather than a blank.

§9.2's rubric weights five components, four of which are M4's and M5's. The confidence rating draws
on five inputs and **three of them already exist** — coverage, quarters of history, data-integrity
findings — which is exactly what makes a partial number dangerous rather than unavailable: it would
render on the same 0–100 scale as the real one and be wrong in a direction nobody can see. So no
partial score, no partial rating, and a labelled slot rather than an empty space — the same call
§4.5 makes for its declared-but-null keys, and the reason M5 filling it is a one-line diff.
"""

ABSENT_SECTIONS: Final = (
    ("Forecast — revenue, margin and FCF ranges, DCF bridge, sensitivity", "M5"),
    ("Quality scores (Piotroski F, Altman Z, Beneish M) and peer percentiles", "M4"),
    ("What changed — 8-K events, filing diffs, insider and short-interest trend", "M4.5"),
    ("Narrative risk analysis from filing text", "M6"),
    ("Measured forecast accuracy and interval calibration", "M7"),
)
"""What this report does not contain, and when it will.

Rendered in caveats on **every** run, not only when something is missing. A reader who does not know
what is absent cannot calibrate what is present, and the most likely misreading of an M3 report is
that the tool has no opinion on valuation rather than that the opinion has not been built.
"""

_SNAPSHOT_METRICS: Final = (
    (Metric.REVENUE, "Revenue"),
    (Metric.NET_INCOME, "Net income"),
    (Metric.OPERATING_CASH_FLOW, "Operating cash flow"),
    (Metric.ASSETS, "Total assets"),
    (Metric.EQUITY, "Total equity"),
)

_MISSING_COHORT: Final = (
    "Current multiples vs. peer percentiles — the SIC cohort arrives with ROADMAP M4."
)
_MISSING_ROIC: Final = "ROIC vs. WACC — WACC is the CAPM build in ROADMAP M5."
_MISSING_DESCRIPTION: Final = (
    "Business description is the SIC classification only. A written one comes from 10-K Item 1, "
    "summarized under ROADMAP M6."
)


# ---------------------------------------------------------------------------
# Leaf shapes
# ---------------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class Row:
    """One table row: a label, already-formatted cells, and a note column."""

    label: str
    cells: tuple[str, ...]
    note: str = ""


@dataclass(frozen=True, slots=True)
class Table:
    caption: str
    columns: tuple[str, ...]
    rows: tuple[Row, ...]
    note_heading: str = ""
    footnote: str = ""

    @property
    def is_empty(self) -> bool:
        return not self.rows or not self.columns


@dataclass(frozen=True, slots=True)
class Cover:
    ticker: str
    name: str
    as_of: str
    verdict: str
    verdict_note: str
    confidence: str
    confidence_note: str
    coverage_line: str
    quarters_line: str
    disclaimer: str


@dataclass(frozen=True, slots=True)
class Snapshot:
    rows: tuple[Row, ...]
    market_cap: str
    market_cap_note: str
    omissions: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class HistorySection:
    charts: tuple[ChartImage, ...]
    omissions: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Caveats:
    coverage: Table
    spine_origin: str
    spine_warning: str
    absent_sections: tuple[tuple[str, str], ...]
    accuracy: str
    gates: tuple[str, ...]
    findings: tuple[Row, ...]


@dataclass(frozen=True, slots=True)
class Appendix:
    annual: Table
    quarterly: Table
    provenance: Table
    sources: Table
    config: tuple[Row, ...]
    manifest_hash: str


@dataclass(frozen=True, slots=True)
class ReportModel:
    """The whole document, as strings.

    ``sources_used`` is not rendered. It exists so ``test_report_model`` can assert that every
    ``Provenance`` behind a rendered figure also appears in ``report.json``'s interned array — which
    is how ROADMAP M3's *"every number traceable to a `SourceRef` in the appendix"* becomes a test
    rather than a claim about how carefully the templates were written.
    """

    cover: Cover
    snapshot: Snapshot
    history: HistorySection
    caveats: Caveats
    appendix: Appendix
    run: RunInfo
    brief: bool
    sources_used: tuple[Provenance, ...]


# ---------------------------------------------------------------------------
# Derived series
# ---------------------------------------------------------------------------
def free_cash_flow(history: FinancialHistory, bucket: Bucket) -> tuple[Datum, ...]:
    """``OPERATING_CASH_FLOW − CAPEX``, per period, both required.

    Capex is positive-as-filed — ``normalize/tags.py`` declares the sign convention and
    ``docs/m2/01-tags.md`` §8 argues it — so this subtracts rather than adds. Getting that backwards
    produces a series that is wrong by twice capex and looks entirely plausible, which is why the
    convention lives in the registry and is not re-decided here.
    """
    cash = {fact.period.end: fact for fact in history.series(Metric.OPERATING_CASH_FLOW, bucket)}
    capex = {fact.period.end: fact for fact in history.series(Metric.CAPEX, bucket)}
    return tuple(
        Datum(
            value=cash[end].value - capex[end].value,
            period=cash[end].period,
            source=Derivation(
                rule="free_cash_flow",
                inputs=(cash[end].source, capex[end].source),
                note="operating cash flow less capital expenditure, capex positive as filed",
            ),
        )
        for end in sorted(set(cash) & set(capex), key=_day)
    )


def margin_series(
    history: FinancialHistory, numerator: Metric, bucket: Bucket
) -> tuple[Datum, ...]:
    """``numerator ÷ REVENUE``, per period, both required and revenue non-zero.

    A margin against zero revenue is undefined rather than infinite, and a pre-revenue biotech is a
    real filer — dropping the period is the only answer that does not print something.
    """
    revenue = {fact.period.end: fact for fact in history.series(Metric.REVENUE, bucket)}
    top = {fact.period.end: fact for fact in history.series(numerator, bucket)}
    return tuple(
        Datum(
            value=top[end].value / revenue[end].value,
            period=top[end].period,
            source=Derivation(
                rule="margin",
                inputs=(top[end].source, revenue[end].source),
                note=f"{numerator} / revenue",
            ),
        )
        for end in sorted(set(revenue) & set(top), key=_day)
        if revenue[end].value != 0
    )


def yoy_series(facts: Sequence[Fact]) -> tuple[Datum, ...]:
    """``(vₜ − vₜ₋₁) ÷ vₜ₋₁`` over **consecutive** periods in the series as given.

    Consecutive in the series, not consecutive in the calendar: a filer with a gap year would
    otherwise get a two-year growth rate labelled as one year's, which overstates it by roughly the
    square. The gap is visible on the chart as a missing point, which is the honest rendering.
    """
    ordered = sorted(facts, key=_fact_day)
    return tuple(
        Datum(
            value=(later.value - earlier.value) / earlier.value,
            period=later.period,
            source=Derivation(
                rule="yoy_growth",
                inputs=(later.source, earlier.source),
                note=f"{earlier.period.end.isoformat()} → {later.period.end.isoformat()}",
            ),
        )
        for earlier, later in pairwise(ordered)
        if earlier.value != 0 and _is_consecutive(earlier.period.end, later.period.end)
    )


def _is_consecutive(earlier: date, later: date) -> bool:
    """Within a year and a quarter of each other — the same ±tolerance the spine uses.

    Not `later.year - earlier.year == 1`, which is false for a filer whose fiscal year end moved by
    a week across a calendar boundary and true for one that skipped a year and shifted.
    """
    return 300 <= (later - earlier).days <= 430


def _day(value: date) -> date:
    return value


def _fact_day(fact: Fact) -> date:
    return fact.period.end


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------
def build_model(history: FinancialHistory, run: RunInfo, *, brief: bool = False) -> ReportModel:
    """Assemble the whole document.

    ``brief`` is carried on the model and changes **nothing else**. The same sections are built with
    the same values; the template decides which of them to render. A brief report that took a
    different data path could disagree with the full one about a figure, and the disagreement would
    be visible only to someone who ran both — so the few milliseconds of formatting nobody reads are
    the price of the guarantee.
    """
    charts = _charts(history)
    cover = _cover(history)
    snapshot = _snapshot(history)
    caveats = _caveats(history)
    appendix = _appendix(history, run)
    used = tuple(source for chart in charts for source in chart.sources) + tuple(
        fact.source
        for store in (history.annual, history.quarterly)
        for facts in store.values()
        for fact in facts
    )
    return ReportModel(
        cover=cover,
        snapshot=snapshot,
        history=HistorySection(charts=charts, omissions=(_MISSING_ROIC,)),
        caveats=caveats,
        appendix=appendix,
        run=run,
        brief=brief,
        sources_used=used,
    )


def _cover(history: FinancialHistory) -> Cover:
    rate = history.coverage.tier_fill_rate(Tier.DCF, Bucket.ANNUAL)
    origin = str(history.coverage.spine.origin)
    qualifier = " against an observed denominator" if origin == "observed" else ""
    return Cover(
        ticker=history.ticker,
        name=history.name,
        as_of=fmt.iso_date(history.as_of),
        verdict=NOT_ASSESSED,
        verdict_note="Score and confidence rating arrive with the forecast engine (ROADMAP M5).",
        confidence=NOT_ASSESSED,
        confidence_note=(
            "No partial rating is shown. Three of the five inputs DESIGN §9.2 names exist today; "
            "a number built from three of five reads on the same scale as the real one."
        ),
        coverage_line=f"Tier-1 annual coverage {fmt.percent(rate)}{qualifier}",
        quarters_line=f"{fmt.count(history.quarters_available)} quarters of history",
        disclaimer=DISCLAIMER,
    )


def _snapshot(history: FinancialHistory) -> Snapshot:
    rows: list[Row] = [
        Row(label="CIK", cells=(str(history.cik),)),
        Row(label="SIC", cells=(_sic(history),)),
        Row(label="Fiscal year end", cells=(history.fiscal_year_end or fmt.ABSENT,)),
        Row(
            label="Window",
            cells=(f"{fmt.iso_date(history.window[0])} to {fmt.iso_date(history.window[1])}",),
        ),
        Row(label="Quarters available", cells=(fmt.count(history.quarters_available),)),
    ]
    for metric, label in _SNAPSHOT_METRICS:
        latest = _latest(history.series(metric, Bucket.ANNUAL))
        rows.append(
            Row(
                label=f"{label} (latest FY)",
                cells=(fmt.money(latest.value) if latest is not None else fmt.ABSENT,),
                note=fmt.iso_date(latest.period.end) if latest is not None else "",
            )
        )
    fcf = free_cash_flow(history, Bucket.ANNUAL)
    rows.append(
        Row(
            label="Free cash flow (latest FY)",
            cells=(fmt.money(fcf[-1].value) if fcf else fmt.ABSENT,),
            note="derived: operating cash flow − capex" if fcf else "",
        )
    )

    cap, note = fmt.ABSENT, ""
    if history.market_cap is not None:
        value, derivation = history.market_cap
        cap = fmt.money(value)
        note = derivation.note or derivation.rule
    return Snapshot(
        rows=tuple(rows),
        market_cap=cap,
        market_cap_note=note,
        omissions=(_MISSING_COHORT, _MISSING_DESCRIPTION),
    )


def _charts(history: FinancialHistory) -> tuple[ChartImage, ...]:
    annual = Bucket.ANNUAL
    revenue = history.series(Metric.REVENUE, annual)
    return (
        build(
            ChartSpec(
                chart_id="revenue",
                title="Revenue and year-over-year growth",
                kind=ChartKind.BARS_WITH_RATE_LINE,
                y_label="USD millions",
                rate_label="YoY",
            ),
            (
                PlotSeries.of_facts("Revenue", revenue),
                PlotSeries(
                    label="YoY growth",
                    points=yoy_series(revenue),
                    colour=SERIES_SECONDARY,
                    rate=True,
                ),
            ),
            reason=_absence(history, Metric.REVENUE, "Revenue"),
        ),
        build(
            ChartSpec(
                chart_id="margins",
                title="Gross, operating and net margin",
                kind=ChartKind.LINES,
                y_label="% of revenue",
                percent_axis=True,
            ),
            (
                PlotSeries(
                    label="Gross",
                    points=margin_series(history, Metric.GROSS_PROFIT, annual),
                    colour=SERIES_PRIMARY,
                ),
                PlotSeries(
                    label="Operating",
                    points=margin_series(history, Metric.OPERATING_INCOME, annual),
                    colour=SERIES_SECONDARY,
                ),
                PlotSeries(
                    label="Net",
                    points=margin_series(history, Metric.NET_INCOME, annual),
                    colour=SERIES_TERTIARY,
                ),
            ),
            reason=_absence(history, Metric.REVENUE, "Margins"),
        ),
        build(
            ChartSpec(
                chart_id="fcf_vs_net_income",
                title="Free cash flow vs. net income",
                kind=ChartKind.LINES,
                y_label="USD millions",
            ),
            (
                PlotSeries(
                    label="Free cash flow",
                    points=free_cash_flow(history, annual),
                    colour=SERIES_PRIMARY,
                ),
                PlotSeries.of_facts(
                    "Net income",
                    history.series(Metric.NET_INCOME, annual),
                    colour=SERIES_SECONDARY,
                ),
            ),
        ),
        build(
            ChartSpec(
                chart_id="balance_sheet",
                title="Assets, liabilities and equity",
                kind=ChartKind.GROUPED_BARS,
                y_label="USD millions",
            ),
            (
                PlotSeries.of_facts("Assets", history.series(Metric.ASSETS, annual)),
                PlotSeries.of_facts(
                    "Liabilities",
                    history.series(Metric.LIABILITIES, annual),
                    colour=SERIES_SECONDARY,
                ),
                PlotSeries.of_facts(
                    "Equity", history.series(Metric.EQUITY, annual), colour=SERIES_TERTIARY
                ),
            ),
            reason=_absence(history, Metric.ASSETS, "Balance sheet"),
        ),
        build(
            ChartSpec(
                chart_id="share_count",
                title="Diluted weighted-average shares",
                kind=ChartKind.BARS,
                y_label="millions of shares",
            ),
            (
                PlotSeries.of_facts(
                    "Diluted shares",
                    history.series(Metric.SHARES_DILUTED_WEIGHTED, annual),
                    colour=SERIES_MUTED,
                ),
            ),
            reason=_absence(history, Metric.SHARES_DILUTED_WEIGHTED, "Share count"),
        ),
    )


def _absence(history: FinancialHistory, metric: Metric, title: str) -> str | None:
    """A stated reason when the metric's own coverage explains the gap, else ``None``.

    Returning ``None`` leaves the point-count rule in ``charts.build`` to decide. The distinction is
    the one ``docs/m3/01-charts.md`` §5 asks for: *"no operating income, because banks do not report
    one"* and *"only one annual period in the window"* both produce no chart and mean different
    things, and only the coverage report knows which.
    """
    coverage = history.coverage.for_bucket(Bucket.ANNUAL).get(metric)
    if coverage is None or coverage.filled > 0:
        return None
    if history.coverage.spine.origin != "filings":
        return (
            f"{title} not charted — this filer has no periodic filings in the window, so there is "
            "no reporting calendar to chart against. See § Caveats, data coverage."
        )
    return (
        f"{title} not charted — {metric} has {coverage.filled} of {coverage.expected} annual "
        "periods. See § Caveats, data coverage."
    )


def _caveats(history: FinancialHistory) -> Caveats:
    spine = history.coverage.spine
    origin = str(spine.origin)
    return Caveats(
        coverage=_coverage_table(history),
        spine_origin=(
            f"{origin} — {fmt.count(len(spine.annual_ends))} annual and "
            f"{fmt.count(len(spine.quarterly_ends))} quarterly period ends"
        ),
        spine_warning=(
            "The denominator is observed from the facts themselves rather than from a filing "
            "calendar, which makes every percentage below circular. Read them as a description of "
            "what was tagged, not as a measurement of what is missing."
            if origin == "observed"
            else ""
        ),
        absent_sections=ABSENT_SECTIONS,
        accuracy=(
            "No forecast has been made, so no accuracy has been measured. Walk-forward "
            "backtesting against naive baselines arrives with ROADMAP M7; until it does, any "
            "confidence figure this tool prints would be unvalidated and is therefore not printed."
        ),
        gates=_gates(history),
        findings=tuple(
            Row(label=finding.code, cells=(finding.detail,), note=str(finding.metric or ""))
            for finding in history.coverage.findings
        ),
    )


def _gates(history: FinancialHistory) -> tuple[str, ...]:
    """§6.10's and §5.1's thresholds, **recorded and not enforced**.

    Both suppress a *valuation*, and there is no valuation at M3, so they are information rather
    than consequence and the wording says so. M2 recorded them for exactly this reason and made no
    refusal; repeating the refusal here would be the second copy of a rule M4 and M5 own.
    """
    notices: list[str] = []
    sic = history.sic
    if sic is not None and (6000 <= sic <= 6499 or sic == 6798):
        notices.append(
            f"SIC {sic} is a bank, insurer or REIT. DESIGN §6.10 omits the valuation for these "
            "rather than filling it with a wrong number — a gate that applies from ROADMAP M5."
        )
    if history.quarters_available < 12:
        notices.append(
            f"{history.quarters_available} quarters of history, below the twelve DESIGN §5.1 "
            "requires before a valuation is attempted. Also a gate that applies from ROADMAP M5."
        )
    return tuple(notices)


def _coverage_table(history: FinancialHistory) -> Table:
    rows: list[Row] = []
    for metric in _metric_order():
        annual = history.coverage.for_bucket(Bucket.ANNUAL).get(metric)
        quarterly = history.coverage.for_bucket(Bucket.QUARTERLY).get(metric)
        rows.append(
            Row(
                label=str(metric).replace("_", " "),
                cells=(_fill(annual), _fill(quarterly)),
                note=_tags(annual, quarterly),
            )
        )
    return Table(
        caption="Data coverage by metric",
        columns=("annual", "quarterly"),
        rows=tuple(rows),
        note_heading="tags used",
        footnote=(
            "filled / expected against the period spine. A metric with no tag matched shows "
            f"{fmt.ABSENT} and is not charted."
        ),
    )


def _fill(coverage: MetricCoverage | None) -> str:
    if coverage is None or coverage.expected == 0:
        return fmt.NOT_APPLICABLE
    return f"{coverage.filled}/{coverage.expected} ({fmt.percent(coverage.fill_rate)})"


def _tags(annual: MetricCoverage | None, quarterly: MetricCoverage | None) -> str:
    used: list[str] = []
    for coverage in (annual, quarterly):
        if coverage is None:
            continue
        used.extend(tag for tag in coverage.tags_used if tag not in used)
    return " → ".join(used) if used else fmt.ABSENT


def _appendix(history: FinancialHistory, run: RunInfo) -> Appendix:
    return Appendix(
        annual=_series_table(history, Bucket.ANNUAL),
        quarterly=_series_table(history, Bucket.QUARTERLY),
        provenance=_coverage_table(history),
        sources=_sources_table(history),
        config=tuple(
            Row(label=name, cells=(value,)) for name, value in sorted(run.config.items(), key=_pair)
        ),
        manifest_hash=run.manifest_hash or fmt.ABSENT,
    )


def _series_table(history: FinancialHistory, bucket: Bucket) -> Table:
    """One bucket's full table, at :func:`format.exact` precision.

    Exact rather than scaled, unlike everywhere else in the report. This is the page a reader checks
    against EDGAR, and ``391,035`` cannot be checked while ``391035000000.01`` can — which is also
    what makes the float discipline in ``charts.py`` assertable.
    """
    ends = tuple(
        sorted(
            {
                fact.period.end
                for metric in _metric_order()
                for fact in history.series(metric, bucket)
            },
            key=_day,
        )
    )
    rows: list[Row] = []
    for metric in _metric_order():
        by_end = {fact.period.end: fact for fact in history.series(metric, bucket)}
        rows.append(
            Row(
                label=str(metric).replace("_", " "),
                cells=tuple(_exact_cell(by_end.get(end)) for end in ends),
                note=_unit(by_end),
            )
        )
    return Table(
        caption=f"{str(bucket).capitalize()} series, as filed",
        columns=tuple(fmt.iso_date(end) for end in ends),
        rows=tuple(rows),
        note_heading="unit",
        footnote="Values exactly as filed — unscaled and unrounded, for checking against EDGAR.",
    )


def _exact_cell(fact: Fact | None) -> str:
    return fmt.ABSENT if fact is None else fmt.exact(fact.value)


def _unit(by_end: Mapping[date, Fact]) -> str:
    units = sorted({fact.unit for fact in by_end.values()}, key=_text)
    return ", ".join(units) if units else fmt.ABSENT


def _sources_table(history: FinancialHistory) -> Table:
    """§9.1's tag-provenance appendix, **interned by the serializer rather than re-walked here.**

    ``docs/m2/04-serialize.md`` observed that the ``sources`` array *"is also §9.1's appendix,
    already deduplicated, so M3 renders it directly instead of walking every fact to collect
    distinct refs."* Two walks would be two chances to disagree about what "distinct" means, in the
    one table whose entire job is to be checkable.
    """
    rows = tuple(
        Row(
            label=str(index),
            cells=(
                ref.accession.value,
                f"{ref.taxonomy or fmt.ABSENT}:{ref.tag or fmt.ABSENT}",
                ref.form,
                fmt.iso_date(ref.filed),
            ),
            note=ref.url,
        )
        for index, ref in enumerate(intern_sources(history))
    )
    return Table(
        caption="Sources",
        columns=("#", "accession", "taxonomy:tag", "form", "filed"),
        rows=rows,
        note_heading="url",
    )


def _sic(history: FinancialHistory) -> str:
    if history.sic is None:
        return fmt.ABSENT
    return (
        f"{history.sic} — {history.sic_description}"
        if history.sic_description
        else str(history.sic)
    )


def _latest(facts: Sequence[Fact]) -> Fact | None:
    return max(facts, key=_fact_day) if facts else None


def _metric_order() -> tuple[Metric, ...]:
    """Tier 1 then tier 2, in registry order — the order ``investo facts`` prints."""
    return (*metrics_in_tier(Tier.DCF), *metrics_in_tier(Tier.QUALITY))


def _pair(item: tuple[str, str]) -> str:
    return item[0]


def _text(value: str) -> str:
    return value
